version: '3.7'

services:
  janus-gateway:
    image: 'canyan/janus-gateway:0.10.7'
    command: ["/usr/local/bin/janus"]
#    entrypoint: /bin/bash
    tty: true
    ports:
#      janus main port
      - "8088:8088"
#      janus admin port
      - "7088:7088"
    volumes:
      - "./_janus:/usr/local/etc/janus/:ro"
      - "./_janus_plugins:/usr/local/lib/janus/plugins/:ro"
      - "demos:/usr/local/share/janus/demos/"
    restart: always
    depends_on:
      - event_consumer
      - message_consumer

  redis:
    image: redis

  pg:
    image: postgres:13
    volumes:
      - "./_data:/var/lib/postgresql/data"
#    ports:
#      - "25432:5432"

  event_consumer:
    build: .
    env_file:
      - env/docker.env
    command: uvicorn --host 0.0.0.0 --port 15000 event_consumer:app
    depends_on:
      - pg
      - redis

  #    command: python event_consumer.py

  message_consumer:
    build: .
    env_file:
      - env/docker.env
    command: uvicorn --host 0.0.0.0 --port 16000 message_consumer:app
    depends_on:
      - pg
      - redis

  server:
    build: .
    env_file:
      - env/docker.env
    environment:
      - JANUS_GATEWAY_URL=http://janus-gateway:8088/janus
      - JANUS_GATEWAY_ADMIN_URL=http://janus-gateway:7088/admin
    ports:
      - "8000:8000"
    command: uvicorn --host 0.0.0.0 --port 8000 main:fast_api
    depends_on:
      - pg
      - redis
#    command: python message_consumer.py

volumes:
  demos:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/Users/bigblackbug/projects/harddays/swipe-backend/_janus_demo"
