version: '3.7'

services:
  redis:
    image: redis

  pg:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "${APP_DIR:?unset}/data:/var/lib/postgresql/data"

  server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - SWIPE_PORT=8000
    ports:
      - "80:8000"
    command: python main.py
    depends_on:
      - pg
      - redis

  chat_server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    ports:
      - "16000:16000"
    command: uvicorn --host 0.0.0.0 --port 16000 ws_servers.chat_server:app
    depends_on:
      - pg
      - redis
      - server

  matchmaking_server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    ports:
      - "17000:17000"
    command: python ws_servers/matchmaking_server.py
    depends_on:
      - pg
      - redis
      - server
