version: '3.7'

volumes:
  letsencrypt:
    external:
      name: letsencrypt_keys

services:
  redis:
    image: redis
    restart: always
    ports:
      - "26379:6379"

  turn_server:
    image: coturn/coturn
    network_mode: host
    restart: always
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro

  nginx:
    image: nginx:1.18
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - ./config-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config-nginx/conf.d:/etc/nginx/conf.d:ro
      - ./landing:/home/landing:ro
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - swipe_server
      - chat_server
      - video_matchmaking_server
      - audio_matchmaking_server
      - text_matchmaking_server
      - text_matchmaking_chat_server

  swipe_server:
    image: ${SWIPE_IMAGE:?unset}
    restart: always
    env_file:
      - swipe.env
    environment:
      - CHAT_SERVER_HOST=http://chat_server:80
    entrypoint: python bin/swipe_server.py
    depends_on:
      - redis

  chat_server:
    image: ${SWIPE_IMAGE:?unset}
    restart: always
    env_file:
      - swipe.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/swipe/google-credentials.json
    volumes:
      - './google-credentials.json:/etc/swipe/google-credentials.json:ro'
    entrypoint: python bin/chat_server.py
    depends_on:
      - swipe_server
      - redis

  video_matchmaking_server:
    image: ${SWIPE_IMAGE:?unset}
    restart: always
    env_file:
      - swipe.env
    environment:
      - CHAT_SERVER_HOST=http://chat_server:80
    entrypoint: python bin/matchmaking_server.py
    depends_on:
      - turn_server
      - redis

  video_matchmaker:
    image: ${SWIPE_IMAGE:?unset}
    restart: on-failure
    env_file:
      - swipe.env
    environment:
      - MATCHMAKING_SERVER_HOST=http://video_matchmaking_server:80
    entrypoint: python bin/matchmaker.py
    depends_on:
      - video_matchmaking_server

  audio_matchmaking_server:
    image: ${SWIPE_IMAGE:?unset}
    restart: always
    env_file:
      - swipe.env
    environment:
      - CHAT_SERVER_HOST=http://chat_server:80
    entrypoint: python bin/matchmaking_server.py
    depends_on:
      - turn_server
      - redis

  audio_matchmaker:
    image: ${SWIPE_IMAGE:?unset}
    restart: on-failure
    env_file:
      - swipe.env
    environment:
      - MATCHMAKING_SERVER_HOST=http://audio_matchmaking_server:80
    entrypoint: python bin/matchmaker.py
    depends_on:
      - audio_matchmaking_server

  text_matchmaking_server:
    image: ${SWIPE_IMAGE:?unset}
    restart: always
    env_file:
      - swipe.env
    environment:
      - CHAT_SERVER_HOST=http://chat_server:80
    entrypoint: python bin/matchmaking_server.py
    depends_on:
      - turn_server
      - redis

  text_matchmaker:
    image: ${SWIPE_IMAGE:?unset}
    restart: on-failure
    env_file:
      - swipe.env
    environment:
      - MATCHMAKING_SERVER_HOST=http://text_matchmaking_server:80
    entrypoint: python bin/matchmaker.py
    depends_on:
      - text_matchmaking_server

  text_matchmaking_chat_server:
    image: ${SWIPE_IMAGE:?unset}
    restart: always
    env_file:
      - swipe.env
    environment:
      - CHAT_SERVER_HOST=http://chat_server:80
    entrypoint: python bin/matchmaking_chat_server.py
    depends_on:
      - redis

  logger:
    image: umputun/docker-logger
    restart: always
    environment:
      - LOG_FILES=true
      - LOG_SYSLOG=false
      - INCLUDE_PATTERN=(.*)_server
      - MAX_FILES=9999
      - MAX_SIZE=5000
      - MAX_AGE=9999
      - DEBUG=false

    volumes:
      - /mnt/logs:/srv/logs
      - /var/run/docker.sock:/var/run/docker.sock
