version: '3.7'

services:
  redis:
    image: redis

  pg:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "${APP_DIR:?unset}/data:/var/lib/postgresql/data"

  server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - SWIPE_PORT=8000
    ports:
      - "80:8000"
    entrypoint: python bin/swipe_server.py
    depends_on:
      - pg
      - redis

  chat_server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - CHAT_SERVER_PORT=80
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/swipe/google-credentials.json
    volumes:
      - './google-credentials.json:/etc/swipe/google-credentials.json:ro'
    ports:
      - "16000:80"
    entrypoint: python bin/chat_server.py
    depends_on:
      - server


  video_matchmaking_server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - MATCHMAKING_SERVER_PORT=80
      - CHAT_SERVER_HOST=http://chat_server:80
    ports:
      - "17000:80"
    entrypoint: python bin/matchmaking_server.py

  video_matchmaker:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - MATCHMAKING_SERVER_HOST=http://video_matchmaking_server:80
    entrypoint: python bin/matchmaker.py
    depends_on:
      - video_matchmaking_server

  audio_matchmaking_server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - MATCHMAKING_SERVER_PORT=80
      - CHAT_SERVER_HOST=http://chat_server:80
    ports:
      - "18000:80"
    entrypoint: python bin/matchmaking_server.py

  audio_matchmaker:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - MATCHMAKING_SERVER_HOST=http://audio_matchmaking_server:80
    entrypoint: python bin/matchmaker.py
    depends_on:
      - audio_matchmaking_server
