version: '3.7'

services:
  redis:
    image: redis

  pg:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./_data:/var/lib/postgresql/data"
    ports:
      - "25432:5432"

  server:
    build: .
    env_file:
      - env/docker.env
    environment:
      - SWIPE_PORT=8000
    ports:
      - "8000:8000"
    command: python main.py
    depends_on:
      - pg
      - redis

  chat_server:
    build: .
    env_file:
      - env/docker.env
    ports:
      - "16000:16000"
    command: uvicorn --host 0.0.0.0 --port 16000 ws_servers.chat_server:app
    depends_on:
      - server
      - pg
      - redis

  matchmaking_server:
    build: .
    env_file:
      - env/docker.env
    ports:
      - "17000:17000"
    command: python ws_servers/matchmaking_server.py
