version: '3.7'

services:
  redis:
    image: redis

  pg:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "${APP_DIR:?unset}/data:/var/lib/postgresql/data"

  server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - SWIPE_PORT=8000
    ports:
      - "80:8000"
    entrypoint: python bin/swipe_server.py
    depends_on:
      - pg
      - redis

  chat_server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - CHAT_SERVER_PORT=16000
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/swipe/google-credentials.json
    volumes:
      - './google-credentials.json:/etc/swipe/google-credentials.json:ro'
    ports:
      - "16000:16000"
    entrypoint: python bin/chat_server.py
    depends_on:
      - server

  video_matchmaking_server:
    build: .
    env_file:
      - env/docker.env
    environment:
      - MATCHMAKER_HOST=video_matchmaker
      - MATCHMAKER_PORT=50050
      - MATCHMAKING_SERVER_PORT=80
    ports:
      - "17000:80"
    entrypoint: python bin/matchmaking_server.py
    depends_on:
      - video_matchmaker

  video_matchmaker:
    build: .
    env_file:
      - env/docker.env
    environment:
      - MATCHMAKER_HOST=video_matchmaker
      - MATCHMAKER_PORT=50050
    entrypoint: python bin/matchmaker.py

  audio_matchmaking_server:
    build: .
    env_file:
      - env/docker.env
    environment:
      - MATCHMAKER_HOST=audio_matchmaker
      - MATCHMAKER_PORT=50060
      - MATCHMAKING_SERVER_PORT=80
    ports:
      - "18000:80"
    entrypoint: python bin/matchmaking_server.py
    depends_on:
      - audio_matchmaker

  audio_matchmaker:
    build: .
    env_file:
      - env/docker.env
    environment:
      - MATCHMAKER_HOST=audio_matchmaker
      - MATCHMAKER_PORT=50060
    entrypoint: python bin/matchmaker.py
