version: '3.4'

services:
  letsencrypt:
    image: certbot/certbot:latest
    command: sh -c "certbot certonly --standalone -d dombo.cc -d server.dombo.cc -d chats.dombo.cc -d matchmaking.dombo.cc -d mmchat.dombo.cc --text --agree-tos --email bigblackbugg@gmail.com --server https://acme-v02.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - letsencrypt:/etc/letsencrypt
    environment:
      - TERM=xterm
    ports:
      - "80:80"

volumes:
  letsencrypt:
    name: letsencrypt_keys
