version: '3.7'

services:
  redis:
    image: redis

  pg:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "${APP_DIR:?unset}/data:/var/lib/postgresql/data"

  server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - SWIPE_PORT=8000
    ports:
      - "80:8000"
    entrypoint: python bin/swipe_server.py
    depends_on:
      - pg
      - redis

  chat_server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - CHAT_SERVER_PORT=16000
    ports:
      - "16000:16000"
    entrypoint: python bin/chat_server.py
    depends_on:
      - server

  matchmaking_server:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - MATCHMAKER_HOST=matchmaker
      - MATCHMAKER_PORT=50505
      - MATCHMAKING_SERVER_PORT=17000
    ports:
      - "17000:17000"
    entrypoint: python bin/matchmaking_server.py
    depends_on:
      - matchmaker
      - server

  matchmaker:
    image: ${SWIPE_IMAGE:?unset}
    env_file:
      - swipe.env
    environment:
      - MATCHMAKER_HOST=matchmaker
      - MATCHMAKER_PORT=50505
    entrypoint: python bin/matchmaker.py
