"""add date and comment to blacklist table and reg_date to user

Revision ID: 1289e52e1d8d
Revises: ac3c70aa1d53
Create Date: 2021-11-28 14:39:17.369236

"""
import datetime

import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy import text

revision = '1289e52e1d8d'
down_revision = 'ac3c70aa1d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('block_date', sa.DateTime()))
    op.execute(text("UPDATE blacklist SET block_date = :d").bindparams(
        d=datetime.datetime.now(), ))
    op.alter_column('blacklist', 'block_date', nullable=False)
    op.add_column('blacklist',
                  sa.Column('comment', sa.String(length=200), nullable=True))

    op.add_column('users', sa.Column('registration_date', sa.DateTime()))
    op.execute(text("UPDATE users SET registration_date = :d").bindparams(
        d=datetime.datetime.now(), ))
    op.alter_column('users', 'registration_date', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_date')
    op.drop_column('blacklist', 'comment')
    op.drop_column('blacklist', 'block_date')
    # ### end Alembic commands ###
