"""add cascades to blacklist table

Revision ID: 175f726c41d7
Revises: 2f8bd089e155
Create Date: 2021-11-15 13:52:26.022943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '175f726c41d7'
down_revision = '2f8bd089e155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blacklist_blocked_user_id_fkey', 'blacklist', type_='foreignkey')
    op.drop_constraint('blacklist_blocked_by_id_fkey', 'blacklist', type_='foreignkey')
    op.create_foreign_key(None, 'blacklist', 'users', ['blocked_by_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blacklist', 'users', ['blocked_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blacklist', type_='foreignkey')
    op.drop_constraint(None, 'blacklist', type_='foreignkey')
    op.create_foreign_key('blacklist_blocked_by_id_fkey', 'blacklist', 'users', ['blocked_by_id'], ['id'])
    op.create_foreign_key('blacklist_blocked_user_id_fkey', 'blacklist', 'users', ['blocked_user_id'], ['id'])
    # ### end Alembic commands ###
