"""add notification types field

Revision ID: 314cd30f85c8
Revises: 9abedbe40143
Create Date: 2021-10-19 11:16:25.064619

"""
import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '314cd30f85c8'
down_revision = '9abedbe40143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum_def = postgresql.ENUM('FRIENDS_MESSAGES', 'ALL',
                               name='notificationtypes')
    enum_def.create(op.get_bind())
    op.add_column('users', sa.Column(
        'enabled_notifications',
        sa.Enum('FRIENDS_MESSAGES', 'ALL', name='notificationtypes'),
        nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enabled_notifications')
    enum_def = postgresql.ENUM('FRIENDS_MESSAGES', 'ALL',
                               name='notificationtypes')
    enum_def.drop(op.get_bind())
    # ### end Alembic commands ###
