"""add source field to Chat

Revision ID: 3d9a63ece08e
Revises: b28b9e510e41
Create Date: 2021-11-05 17:24:26.776569

"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

revision = '3d9a63ece08e'
down_revision = 'b28b9e510e41'
branch_labels = None
depends_on = None

enum_values = ['TEXT_LOBBY', 'VIDEO_LOBBY', 'AUDIO_LOBBY', 'DIRECT']
column_name = 'source'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum_def = postgresql.ENUM(*enum_values, name=column_name)
    enum_def.create(op.get_bind())
    op.add_column('chats', sa.Column(
        column_name,
        sa.Enum(*enum_values, name='source')))
    op.execute(text("UPDATE chats SET source = :s").bindparams(
        s='DIRECT'))
    op.alter_column('chats', column_name, nullable=False)
    op.create_unique_constraint('one_chat_per_pair_2', 'chats',
                                ['the_other_person_id', 'initiator_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('one_chat_per_pair_2', 'chats', type_='unique')
    op.drop_column('chats', column_name)
    enum_def = postgresql.ENUM(*enum_values, name=column_name)
    enum_def.drop(op.get_bind())
    # ### end Alembic commands ###
