"""add smoking and drinking fields

Revision ID: 4c50461fa935
Revises: 87fea1a11a7f
Create Date: 2021-10-15 17:53:15.874864

"""
import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '4c50461fa935'
down_revision = '87fea1a11a7f'
branch_labels = None
depends_on = None

enum_values = ['NEVER', 'SOMETIMES', 'REGULARLY']


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum_def = \
        postgresql.ENUM(*enum_values, name='recurrence_rate')
    enum_def.create(op.get_bind())

    column_def = sa.Enum(*enum_values, name='recurrence_rate')
    op.add_column('users', sa.Column('smoking', column_def, nullable=False))
    op.add_column('users', sa.Column('drinking', column_def, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'drinking')
    op.drop_column('users', 'smoking')
    recurrence_rate = postgresql.ENUM(*enum_values, name='recurrence_rate')
    recurrence_rate.drop(op.get_bind())
    # ### end Alembic commands ###
