"""update default values for bio

Revision ID: 60f6a7d20ff1
Revises: 37a57e965662
Create Date: 2021-11-29 18:13:38.144904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import text

revision = '60f6a7d20ff1'
down_revision = '37a57e965662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("UPDATE users SET bio = :d WHERE bio=''").bindparams(
        d='👋 Я здесь недавно', ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
