"""remove provider_user_id column from AuthInfo

Revision ID: 6974c151deef
Revises: 98c924d84ebe
Create Date: 2021-10-20 19:49:52.977099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6974c151deef'
down_revision = '98c924d84ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
