"""add cascade deletes on Chat, ChatMessage from User

Revision ID: 6edd9b969fe3
Revises: eb2655479cbf
Create Date: 2021-11-10 17:13:32.449702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6edd9b969fe3'
down_revision = 'eb2655479cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_info', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'auth_info', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chat_messages_sender_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chats_initiator_id_fkey', 'chats', type_='foreignkey')
    op.drop_constraint('chats_the_other_person_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['initiator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chats', 'users', ['the_other_person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_auth_info_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'auth_info_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_info_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_auth_info_id_fkey', 'users', 'auth_info', ['auth_info_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_the_other_person_id_fkey', 'chats', 'users', ['the_other_person_id'], ['id'])
    op.create_foreign_key('chats_initiator_id_fkey', 'chats', 'users', ['initiator_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_sender_id_fkey', 'chat_messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'auth_info', type_='foreignkey')
    op.drop_column('auth_info', 'user_id')
    # ### end Alembic commands ###
