"""add is_liked field to chat message

Revision ID: 8112872402ab
Revises: 99d4934ce57d
Create Date: 2021-10-31 22:40:51.204338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8112872402ab'
down_revision = '99d4934ce57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_liked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_liked')
    # ### end Alembic commands ###
