"""add zodiac_sign field

Revision ID: 87fea1a11a7f
Revises: 535fab273fdd
Create Date: 2021-10-15 16:56:26.582465

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '87fea1a11a7f'
down_revision = '535fab273fdd'
branch_labels = None
depends_on = None

enum_values = ['ARIES', 'TAURUS', 'GEMINI',
               'CANCER', 'LEO', 'VIRGO', 'LIBRA',
               'SCORPIO', 'SAGITTARIUS',
               'CAPRICORN', 'AQUARIUS', 'PISCES']

column_name = 'zodiac_sign'


def upgrade():
    enum_def = postgresql.ENUM(*enum_values, name=column_name)
    enum_def.create(op.get_bind())

    op.add_column(
        'users', sa.Column(column_name,
                           sa.Enum(*enum_values, name=column_name),
                           nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', column_name)

    enum_def = postgresql.ENUM(*enum_values, name=column_name)
    enum_def.drop(op.get_bind())
    # ### end Alembic commands ###
