"""add zodiac_sign field

Revision ID: 87fea1a11a7f
Revises: 535fab273fdd
Create Date: 2021-10-15 16:56:26.582465

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '87fea1a11a7f'
down_revision = '535fab273fdd'
branch_labels = None
depends_on = None


def upgrade():
    zodiacsign = postgresql.ENUM('ARIES', 'TAURUS', 'GEMINI',
                                 'CANCER', 'LEO', 'VIRGO', 'LIBRA',
                                 'SCORPIO', 'SAGITTARIUS',
                                 'CAPRICORN', 'AQUARIUS', 'PISCES',
                                 name='zodiac_sign')
    zodiacsign.create(op.get_bind())

    op.add_column('users', sa.Column('zodiac_sign',
                                     sa.Enum('ARIES', 'TAURUS', 'GEMINI',
                                             'CANCER', 'LEO', 'VIRGO', 'LIBRA',
                                             'SCORPIO', 'SAGITTARIUS',
                                             'CAPRICORN', 'AQUARIUS', 'PISCES',
                                             name='zodiac_sign'),
                                     nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zodiac_sign')

    zodiacsign = postgresql.ENUM('ARIES', 'TAURUS', 'GEMINI',
                                 'CANCER', 'LEO', 'VIRGO', 'LIBRA',
                                 'SCORPIO', 'SAGITTARIUS',
                                 'CAPRICORN', 'AQUARIUS', 'PISCES',
                                 name='zodiac_sign')
    zodiacsign.drop(op.get_bind())
    # ### end Alembic commands ###
