"""add creation_date to Chat model

Revision ID: 8dd7ef6dbfba
Revises: ac720e5024cb
Create Date: 2021-11-01 16:21:01.606139

"""
import datetime

import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy import text

revision = '8dd7ef6dbfba'
down_revision = 'ac720e5024cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('creation_date', sa.DateTime()))
    op.execute(text("UPDATE chats SET creation_date = :d").bindparams(
        d=datetime.datetime.now(), ))
    op.alter_column('chats', 'creation_date', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'creation_date')
    # ### end Alembic commands ###
