"""update location id type to uuid

Revision ID: 986e52eaf84f
Revises: e52bc1909b94
Create Date: 2021-10-17 19:36:15.937582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '986e52eaf84f'
down_revision = 'e52bc1909b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
