"""add blacklist

Revision ID: 98c924d84ebe
Revises: 314cd30f85c8
Create Date: 2021-10-20 19:31:59.284753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98c924d84ebe'
down_revision = '314cd30f85c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('blocked_by_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('blocked_user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocked_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blocked_by_id', 'blocked_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist')
    # ### end Alembic commands ###
