"""add reverse uniqueness constrains on chat models participants

Revision ID: 99d4934ce57d
Revises: 12a33c84108f
Create Date: 2021-10-30 19:35:37.093825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d4934ce57d'
down_revision = '12a33c84108f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
