"""add swipes field

Revision ID: 9abedbe40143
Revises: 986e52eaf84f
Create Date: 2021-10-18 16:30:02.597308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abedbe40143'
down_revision = '986e52eaf84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('swipes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'swipes')
    # ### end Alembic commands ###
