"""add deactivation_date field to User

Revision ID: 9d8c960823ba
Revises: 6b10ba92d46e
Create Date: 2021-12-20 16:29:48.003069

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9d8c960823ba'
down_revision = '6b10ba92d46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('deactivation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivation_date')
    # ### end Alembic commands ###
