"""update default fields on user columns

Revision ID: ad5d1aaf13c9
Revises: 1bc8c29f42be
Create Date: 2021-10-28 17:01:40.429057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad5d1aaf13c9'
down_revision = '1bc8c29f42be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'ATTACK_HELICOPTER', name='gender'),
               nullable=True)
    op.alter_column('users', 'smoking',
               existing_type=postgresql.ENUM('NEVER', 'SOMETIMES', 'REGULARLY', name='recurrence_rate'),
               nullable=True)
    op.alter_column('users', 'drinking',
               existing_type=postgresql.ENUM('NEVER', 'SOMETIMES', 'REGULARLY', name='recurrence_rate'),
               nullable=True)
    op.alter_column('users', 'enabled_notifications',
               existing_type=postgresql.ENUM('FRIENDS_MESSAGES', 'ALL', name='notificationtypes'),
               nullable=True)
    op.alter_column('users', 'instagram_profile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'tiktok_profile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'snapchat_profile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'snapchat_profile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'tiktok_profile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'instagram_profile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'enabled_notifications',
               existing_type=postgresql.ENUM('FRIENDS_MESSAGES', 'ALL', name='notificationtypes'),
               nullable=False)
    op.alter_column('users', 'drinking',
               existing_type=postgresql.ENUM('NEVER', 'SOMETIMES', 'REGULARLY', name='recurrence_rate'),
               nullable=False)
    op.alter_column('users', 'smoking',
               existing_type=postgresql.ENUM('NEVER', 'SOMETIMES', 'REGULARLY', name='recurrence_rate'),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'ATTACK_HELICOPTER', name='gender'),
               nullable=False)
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
