"""add firebase_token field

Revision ID: ae36c5552a05
Revises: 175f726c41d7
Create Date: 2021-11-15 16:38:02.813306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae36c5552a05'
down_revision = '175f726c41d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'firebase_token')
    # ### end Alembic commands ###
