"""change type of User.rating field to float

Revision ID: b28b9e510e41
Revises: 8dd7ef6dbfba
Create Date: 2021-11-01 16:54:25.271447

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b28b9e510e41'
down_revision = '8dd7ef6dbfba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rating', default=0.0,
                    type_=sa.Float, nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rating', default=0.0,
                    type_=sa.Integer, nullable=True)
    # ### end Alembic commands ###
