"""add cascade delete on GlobalChatMessage.sender_id

Revision ID: babc194ec784
Revises: f55b2820cc18
Create Date: 2021-11-10 19:59:21.607710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babc194ec784'
down_revision = 'f55b2820cc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('global_chat_messages_sender_id_fkey', 'global_chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'global_chat_messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'global_chat_messages', type_='foreignkey')
    op.create_foreign_key('global_chat_messages_sender_id_fkey', 'global_chat_messages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###
