"""add reverse uniqueness constrains on chat models participants

Revision ID: c9bbb993d9e1
Revises: 12a33c84108f
Create Date: 2021-10-30 14:24:55.803590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bbb993d9e1'
down_revision = '12a33c84108f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('one_chat_per_pair_2', 'chats', ['the_other_person_id', 'initiator_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('one_chat_per_pair_2', 'chats', type_='unique')
    # ### end Alembic commands ###
