"""add location

Revision ID: e52bc1909b94
Revises: e991fa3bf0de
Create Date: 2021-10-17 19:05:57.676354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e52bc1909b94'
down_revision = 'e991fa3bf0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'country', name='_location')
    )
    op.add_column('users', sa.Column('location_id',
                                     postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'users', 'location', ['location_id'], ['id'])
    op.drop_column('users', 'coordinates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    op.drop_table('location')
    # ### end Alembic commands ###
