"""add coordinates field to User

Revision ID: e79878137634
Revises: 8ae2b7e01889
Create Date: 2021-10-13 18:12:24.312003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79878137634'
down_revision = '8ae2b7e01889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coordinates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coordinates')
    # ### end Alembic commands ###
