"""add social links

Revision ID: e991fa3bf0de
Revises: 4c50461fa935
Create Date: 2021-10-15 18:22:03.230624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e991fa3bf0de'
down_revision = '4c50461fa935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram_profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tiktok_profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('snapchat_profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'snapchat_profile')
    op.drop_column('users', 'tiktok_profile')
    op.drop_column('users', 'instagram_profile')
    # ### end Alembic commands ###
