"""increase name field size

Revision ID: f27b7d4742e4
Revises: 6974c151deef
Create Date: 2021-10-21 17:23:22.522717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27b7d4742e4'
down_revision = '6974c151deef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
