"""replace avatar with avatar_id

Revision ID: f87217fd9f12
Revises: ae36c5552a05
Create Date: 2021-11-20 17:47:03.950992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f87217fd9f12'
down_revision = 'ae36c5552a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', sa.String(), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###
