"""add indices on a lot of tables

Revision ID: fdecaec44dc9
Revises: 1289e52e1d8d
Create Date: 2021-11-29 13:44:02.417882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdecaec44dc9'
down_revision = '1289e52e1d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_auth_provider_provider', 'auth_info', ['auth_provider'], unique=False)
    op.create_index('idx_auth_provider_provider_user_id', 'auth_info', ['provider_user_id'], unique=False)
    op.create_index('idx_blacklist_blocked_by', 'blacklist', ['blocked_by_id'], unique=False)
    op.create_index('idx_blacklist_blocked_user', 'blacklist', ['blocked_user_id'], unique=False)
    op.create_index('chat_message_sender_id', 'chat_messages', ['sender_id'], unique=False)
    op.create_index('chat_message_timestamp', 'chat_messages', ['timestamp'], unique=False)
    op.create_index('chat_initiator_id', 'chats', ['initiator_id'], unique=False)
    op.create_index('chat_the_other_person_id', 'chats', ['the_other_person_id'], unique=False)
    op.create_index('global_chat_message_timestamp', 'global_chat_messages', ['timestamp'], unique=False)
    op.create_index('idx_location_city', 'location', ['city'], unique=False)
    op.create_index('idx_location_country', 'location', ['country'], unique=False)
    op.create_index('idx_user_date_of_birth', 'users', ['date_of_birth'], unique=False)
    op.create_index('idx_user_gender', 'users', ['gender'], unique=False)
    op.create_index('idx_user_rating', 'users', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_rating', table_name='users')
    op.drop_index('idx_user_gender', table_name='users')
    op.drop_index('idx_user_date_of_birth', table_name='users')
    op.drop_index('idx_location_country', table_name='location')
    op.drop_index('idx_location_city', table_name='location')
    op.drop_index('global_chat_message_timestamp', table_name='global_chat_messages')
    op.drop_index('chat_the_other_person_id', table_name='chats')
    op.drop_index('chat_initiator_id', table_name='chats')
    op.drop_index('chat_message_timestamp', table_name='chat_messages')
    op.drop_index('chat_message_sender_id', table_name='chat_messages')
    op.drop_index('idx_blacklist_blocked_user', table_name='blacklist')
    op.drop_index('idx_blacklist_blocked_by', table_name='blacklist')
    op.drop_index('idx_auth_provider_provider_user_id', table_name='auth_info')
    op.drop_index('idx_auth_provider_provider', table_name='auth_info')
    # ### end Alembic commands ###
