name: Docker Image CI

on:
  push:
    branches: 
      - feature-*

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_ACCESS_TOKEN }}    

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag swipe/swipe-backend:$(date +%s)

    - run: |
        doctl registry login
        docker push swipe/swipe-backend
    
