name: Docker Image CI

on:
  push:
    branches:
      - 'main'
env:
  APP_DIR: /opt/swipe
  SWIPE_IMAGE: cr.yandex/crpju5a53b9mblhf6ebg/swipe/swipe-backend:latest
  SWIPE_LOCAL_IMAGE: swipe/swipe-backend:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v0.1-alpha
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ env.SWIPE_IMAGE }}
        docker push ${{ env.SWIPE_IMAGE }}

    - name: Copy docker-compose
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.YC_SERVER_HOST }}
        username: swipe
        port: 22
        key: ${{ secrets.YC_SSH_KEY }}
        source: "docker-compose-le.yml,docker-compose-prod.yml"
        target: ${{ env.APP_DIR }}

    - name: Copy nginx config
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.YC_SERVER_HOST }}
        username: swipe
        port: 22
        key: ${{ secrets.YC_SSH_KEY }}
        source: "config-nginx/*"
        target: ${{ env.APP_DIR }}

    - name: Start swipe
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.YC_SERVER_HOST }}
        username: swipe
        port: 22
        key: ${{ secrets.YC_SSH_KEY }}
        script: |
          set -e
          set -x

          export PATH="/home/swipe/yandex-cloud/bin:${PATH}"
          export SWIPE_IMAGE=${{env.SWIPE_IMAGE}}
          export APP_DIR=${{env.APP_DIR}}

          docker-compose -f ${{ env.APP_DIR }}/docker-compose-prod.yml pull
          docker-compose -f ${{ env.APP_DIR }}/docker-compose-prod.yml up -d
          docker exec swipe_nginx_1 nginx -s reload
